.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. litecoinz_qt test_litecoinz_qt
clean: FORCE
	$(MAKE) -C .. litecoinz_qt_clean test_litecoinz_qt_clean
check: FORCE
	$(MAKE) -C .. test_litecoinz_qt_check
litecoinz-qt litecoinz-qt.exe: FORCE
	 $(MAKE) -C .. litecoinz_qt
